import React,{useEffect,useState} from 'react';
import {admin,rpc} from '../api.js';

const Field=({label,...props})=><label>{label}<input {...props}/></label>;
export default function Services({account,notify}){
  const [pds,setPds]=useState(null),[feed,setFeed]=useState(null),[relay,setRelay]=useState(null);
  const load=()=>Promise.allSettled([admin('pds','status'),admin('server','status'),admin('relay','status')]).then(([a,b,c])=>{if(a.value)setPds(a.value);if(b.value)setFeed(b.value);if(c.value)setRelay(c.value)});
  useEffect(()=>{load()},[]); const save=async(agent,state,setter)=>{try{setter(await admin(agent,'configure',state));notify(`${agent} configuration saved`)}catch(e){notify(e.message,true)}};
  return <>
    <div className="section-head"><h2>PDS control</h2></div><div className="server-status">Configure and operate the AT repository hosted by this ship. Its origin must be publicly reachable over HTTPS.</div>
    {!pds?<div className="empty"><span className="spinner"/></div>:<><div className="server-status">{pds.enabled?'live':'disabled'} · {pds.records||0} records · {pds.blobs||0} blobs</div><form className="form-body" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save('pds',{enabled:f.has('enabled'),origin:f.get('origin').replace(/\/$/,''),serviceDid:f.get('serviceDid'),did:f.get('did'),handle:f.get('handle'),...(f.get('appPassword')?{appPassword:f.get('appPassword')}:{})},setPds)}}><Field label="public HTTPS origin" name="origin" defaultValue={pds.origin} required/><Field label="service DID" name="serviceDid" defaultValue={pds.serviceDid} required/><Field label="account DID" name="did" defaultValue={pds.did} required/><Field label="account handle" name="handle" defaultValue={pds.handle} required/><Field label="app password" name="appPassword" type="password" placeholder="leave blank to preserve it"/><label><input name="enabled" type="checkbox" defaultChecked={pds.enabled}/> serve repository and authorization endpoints</label><div className="form-row"><button className="primary">save PDS config</button><button className="ghost" type="button" onClick={()=>admin('pds','cleanup',{}).then(load)}>clean blobs</button></div></form></>}
    <div className="section-head"><h2>feed generator</h2></div>{feed&&<form className="form-body" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save('server',{enabled:f.has('enabled'),did:f.get('did'),endpoint:f.get('endpoint').replace(/\/$/,''),feedUri:f.get('feedUri')},setFeed)}}><Field label="service DID" name="did" defaultValue={feed.did}/><Field label="public HTTPS endpoint" name="endpoint" defaultValue={feed.endpoint}/><Field label="feed record URI" name="feedUri" defaultValue={feed.feedUri}/><label><input name="enabled" type="checkbox" defaultChecked={feed.enabled}/> serve publicly</label><button className="primary">save server config</button></form>}
    <div className="section-head"><h2>event relay</h2></div>{relay&&<form className="form-body" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save('relay',{enabled:f.has('enabled'),token:f.get('token'),upstream:f.get('upstream'),allowlist:f.get('allowlist').split(',').map(x=>x.trim()).filter(Boolean),maxEvents:f.get('maxEvents')},setRelay)}}><Field label="webhook bearer token" name="token" type="password"/><Field label="upstream Ames ship" name="upstream" defaultValue={relay.upstream}/><Field label="ships allowed to subscribe" name="allowlist" defaultValue={(relay.allowlist||[]).join(', ')}/><Field label="bounded event history" name="maxEvents" defaultValue={relay.maxEvents||250}/><label><input name="enabled" type="checkbox" defaultChecked={relay.enabled}/> accept adapter webhooks</label><button className="primary">save relay config</button></form>}
  </>;
}
