import React,{useCallback,useEffect,useState} from 'react';
import {api,rpc,uploadBlob} from './api.js';
import Post,{ago} from './components/Post.jsx';
import Profile from './components/Profile.jsx';
import Services from './components/Services.jsx';

const Empty=({children})=><div className="empty">{children}</div>;
export default function App(){
  const [account,setAccount]=useState(null),[ready,setReady]=useState(false),[route,setRoute]=useState({view:'root'}),[feed,setFeed]=useState([]),[results,setResults]=useState([]),[notices,setNotices]=useState([]),[people,setPeople]=useState([]),[identity,setIdentity]=useState(null),[toast,setToast]=useState(null),[theme,setTheme]=useState(localStorage.getItem('atpro-theme')||'system');
  const notify=(message,bad=false)=>{setToast({message,bad});setTimeout(()=>setToast(null),4200)};
  const navigate=useCallback(next=>{setRoute(next);history.pushState({atpro:true,...next},'',location.href)},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme==='system'?'':theme;localStorage.setItem('atpro-theme',theme)},[theme]);
  useEffect(()=>{history.replaceState({atpro:true,view:'root',sentinel:true},'',location.href);history.pushState({atpro:true,view:'root'},'',location.href);const pop=e=>{if(e.state?.sentinel)return history.forward();setRoute(e.state?.atpro?e.state:{view:'root'})};addEventListener('popstate',pop);Promise.all([api('status'),api('identity')]).then(([s,i])=>{setAccount(s.connected?s:null);setIdentity(i);if(s.connected){const next={view:'timeline'};setRoute(next);history.pushState({atpro:true,...next},'',location.href)}}).catch(e=>notify(e.message,true)).finally(()=>setReady(true));return()=>removeEventListener('popstate',pop)},[]);
  const callRpc=async(...args)=>{try{return await rpc(...args)}catch(e){if(e.status===401){const s=await api('refresh',{});setAccount(s);return rpc(...args)}throw e}};
  const loadTimeline=useCallback(async()=>{try{setFeed((await callRpc('pds','GET','app.bsky.feed.getTimeline','?limit=40')).feed||[])}catch(e){notify(e.message,true)}},[account]);
  useEffect(()=>{if(account&&route.view==='timeline')loadTimeline();if(account&&route.view==='notifications')callRpc('pds','GET','app.bsky.notification.listNotifications','?limit=50').then(x=>setNotices(x.notifications||[])).catch(e=>notify(e.message,true));if(account&&route.view==='people'){const nsid=route.kind==='followers'?'app.bsky.graph.getFollowers':'app.bsky.graph.getFollows';callRpc('pds','GET',nsid,`?actor=${encodeURIComponent(route.actor)}&limit=100`).then(x=>setPeople(x[route.kind==='followers'?'followers':'follows']||[])).catch(e=>notify(e.message,true))}},[account,route]);
  const openActor=actor=>navigate({view:'profile',actor,mode:'posts'}),openThread=uri=>navigate({view:'thread',uri});
  const toggle=async(action,post)=>{try{const existing=action==='like'?post.viewer?.like:post.viewer?.repost;if(existing){const [,repo,collection,rkey]=existing.match(/^at:\/\/([^/]+)\/([^/]+)\/([^/]+)$/)||[];await callRpc('pds','POST','com.atproto.repo.deleteRecord','',{repo:account.did,collection,rkey})}else{const collection=action==='like'?'app.bsky.feed.like':'app.bsky.feed.repost';await callRpc('pds','POST','com.atproto.repo.createRecord','',{repo:account.did,collection,record:{$type:collection,subject:{uri:post.uri,cid:post.cid},createdAt:new Date().toISOString()}})}if(route.view==='timeline')loadTimeline()}catch(e){notify(e.message,true)}};
  const follow=async profile=>{const existing=profile.viewer?.following;if(existing){const [,repo,collection,rkey]=existing.match(/^at:\/\/([^/]+)\/([^/]+)\/([^/]+)$/)||[];await callRpc('pds','POST','com.atproto.repo.deleteRecord','',{repo:account.did,collection,rkey});return {...profile,viewer:{...profile.viewer,following:undefined}}}const x=await callRpc('pds','POST','com.atproto.repo.createRecord','',{repo:account.did,collection:'app.bsky.graph.follow',record:{$type:'app.bsky.graph.follow',subject:profile.did,createdAt:new Date().toISOString()}});return {...profile,viewer:{...profile.viewer,following:x.uri}}};
  const scanContacts=async()=>{try{const x=await api('identity/scan',{});setResults((x.people||[]).map(p=>({did:p.did,handle:p.handle,displayName:p.ship})));navigate({view:'search'});notify(`Found ${x.people?.length||0} of ${x.scanned||0} scanned ships`)}catch(e){notify(e.message,true)}};
  const login=async(e,oauth=false)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(oauth){const x=await api('oauth/start',{identifier:f.get('identifier'),origin:location.origin});location.assign(x.url)}else{const s=await api('login',Object.fromEntries(f));setAccount(s);navigate({view:'timeline'})}}catch(e){notify(e.message,true)}};
  const logout=async()=>{await api('logout',{});setAccount(null);navigate({view:'root'})};
  if(!ready)return <div className="app"><Empty><span className="spinner"/></Empty></div>;
  const content=route.view==='timeline'?<Feed items={feed} {...{openActor,openThread,toggle}}/>:route.view==='profile'?<Profile actor={route.actor} initialMode={route.mode} account={account} onActor={openActor} onThread={openThread} onToggle={toggle} onFollow={follow} onMode={mode=>navigate({...route,mode})} onGraph={(actor,kind)=>navigate({view:'people',actor,kind})}/>:route.view==='search'?<Search results={results} setResults={setResults} openActor={openActor} notify={notify}/>:route.view==='notifications'?<Notifications items={notices} openActor={openActor} openThread={openThread}/>:route.view==='compose'?<Compose account={account} rpc={callRpc} notify={notify} done={()=>navigate({view:'timeline'})}/>:route.view==='people'?<People title={route.kind} people={people} openActor={openActor}/>:route.view==='thread'?<Thread uri={route.uri} rpc={callRpc} account={account} openActor={openActor} openThread={openThread} toggle={toggle} notify={notify}/>:route.view==='serve'?<Services account={account} notify={notify}/>:null;
  return <div className="app"><Header account={account} refresh={()=>route.view==='timeline'&&loadTimeline()} profile={()=>openActor(account.did)}/>{(!account&&route.view!=='serve')?<Connect login={login} openPds={()=>navigate({view:'serve'})}/>:<section className="layout"><Sidebar account={account} route={route} navigate={navigate} logout={logout} identity={identity} setIdentity={setIdentity} theme={theme} setTheme={setTheme} scanContacts={scanContacts}/><main><div className="section-head"><h2>{route.view==='serve'?'PDS control':route.view}</h2></div>{content}</main></section>}{toast&&<div className={`notice show ${toast.bad?'bad':''}`}>{toast.message}</div>}</div>;
}

function Header({account,refresh,profile}){return <header><h1>%atpro</h1><div className="header-tools"><div className="status"><span className={`dot ${account?'on':''}`}/><button className="status-link" disabled={!account} onClick={profile}>{account?`@${account.handle}`:'Not connected'}</button></div><button className="refresh-icon" onClick={refresh}>↻</button></div></header>}
function Connect({login,openPds}){return <section className="panel connect"><div className="eyebrow">Connect an AT account</div><h2>A bridge between worlds.</h2><p>Authorize %atpro with your handle. Keys and tokens remain inside your Urbit agent.</p><form onSubmit={e=>login(e,true)}><label>Handle or DID<input name="identifier" required/></label><button className="primary">Authorize with OAuth</button></form><details className="alternate-auth"><summary>use an app password instead</summary><form onSubmit={login}><label>Handle or DID<input name="identifier" required/></label><label>App password<input name="password" type="password" required/></label><label>PDS service<input name="service" type="url" defaultValue="https://bsky.social" required/></label><button className="primary">Connect through ship</button></form></details><div className="alternate-auth"><button className="ghost" onClick={openPds}>open ship PDS control</button></div></section>}
function Sidebar({account,route,navigate,logout,identity,setIdentity,theme,setTheme,scanContacts}){const go=(view,label)=><button className={route.view===view?'active':''} onClick={()=>navigate({view})}>{label}</button>;return <nav>{account&&<>{go('timeline','timeline')}<button onClick={()=>navigate({view:'profile',actor:account.did,mode:'posts'})}>my profile</button>{go('notifications','notices')}{go('search','find')}{go('compose','write')}</>}{go('serve','PDS + services')}{account&&<details className="settings"><summary>settings</summary><div className="settings-body"><strong>@{account.handle}</strong><div className="meta">{account.did}</div><div className="meta">{identity?.published?`public: @${identity.handle}`:'AT identity is not published'}</div><button className="ghost" onClick={async()=>{const x=await api(identity?.published?'identity/clear':'identity/publish',{});setIdentity(x)}}>{identity?.published?'unpublish':'publish'} AT identity</button><button className="ghost" onClick={scanContacts}>scan contacts</button><button className="danger" onClick={logout}>disconnect</button><label className="setting-option">appearance<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="system">system</option><option value="light">light</option><option value="dark">dark</option></select></label></div></details>}</nav>}
function Feed({items,openActor,openThread,toggle}){return <div className="feed">{items.length?items.map((x,i)=><Post key={x.post?.uri||i} item={x} onActor={openActor} onThread={openThread} onToggle={toggle}/>):<Empty>Your timeline is quiet.</Empty>}</div>}
function Search({results,setResults,openActor,notify}){return <><form className="search-box" onSubmit={async e=>{e.preventDefault();try{setResults((await rpc('public','GET','app.bsky.actor.searchActors',`?q=${encodeURIComponent(new FormData(e.currentTarget).get('q'))}&limit=30`)).actors||[])}catch(e){notify(e.message,true)}}}><input name="q" placeholder="Name, handle, or keyword"/><button className="primary">search</button></form>{results.map(x=><Person key={x.did} person={x} open={openActor}/>)}</>}
const Person=({person,open})=><article className="person" onClick={()=>open(person.did||person.handle)}>{person.avatar?<img className="avatar" src={person.avatar}/>:<div className="avatar"/>}<div><div className="name">{person.displayName||person.handle}</div><div className="handle">@{person.handle}</div><div className="bio">{person.description}</div></div></article>;
function People({title,people,openActor}){return <><div className="subhead">{title}</div>{people.map(x=><Person key={x.did} person={x} open={openActor}/>)}</>}
function Notifications({items,openActor,openThread}){return items.map(x=><article className="notice-row" key={x.uri} onClick={()=>x.reasonSubject?.includes('/app.bsky.feed.post/')?openThread(x.reasonSubject):openActor(x.author.did)}><div className="avatar"/><div><strong>{x.author.displayName||x.author.handle}</strong> {x.reason}<div className="handle">@{x.author.handle} · {ago(x.indexedAt)}</div></div></article>)}
function Compose({account,rpc,notify,done}){return <form className="form-body" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),files=f.getAll('images').filter(x=>x.size),record={$type:'app.bsky.feed.post',text:f.get('text'),createdAt:new Date().toISOString()};try{if(files.length)record.embed={$type:'app.bsky.embed.images',images:await Promise.all(files.slice(0,4).map(async x=>({image:await uploadBlob(x),alt:x.name})))};await rpc('pds','POST','com.atproto.repo.createRecord','',{repo:account.did,collection:'app.bsky.feed.post',record});done()}catch(e){notify(e.message,true)}}}><textarea name="text" maxLength="300" required/><label>images<input name="images" type="file" accept="image/*" multiple/></label><button className="primary">publish</button></form>}
function Thread({uri,rpc,account,openActor,openThread,toggle,notify}){const [node,setNode]=useState(null);const load=()=>rpc('pds','GET','app.bsky.feed.getPostThread',`?uri=${encodeURIComponent(uri)}&depth=8&parentHeight=2`).then(x=>setNode(x.thread)).catch(e=>notify(e.message,true));useEffect(()=>{load()},[uri]);const render=n=>n?.post?<React.Fragment key={n.post.uri}><Post item={n} onActor={openActor} onThread={openThread} onToggle={toggle}/>{(n.replies||[]).map(render)}</React.Fragment>:null;if(!node)return <Empty><span className="spinner"/></Empty>;const parent={uri:node.post.uri,cid:node.post.cid},root=node.post.record?.reply?.root||parent;return <><form className="reply-form" onSubmit={async e=>{e.preventDefault();const text=new FormData(e.currentTarget).get('text');try{await rpc('pds','POST','com.atproto.repo.createRecord','',{repo:account.did,collection:'app.bsky.feed.post',record:{$type:'app.bsky.feed.post',text,reply:{parent,root},createdAt:new Date().toISOString()}});e.currentTarget.reset();load()}catch(e){notify(e.message,true)}}}><textarea name="text" maxLength="300" placeholder="write a reply" required/><button className="primary">reply</button></form>{render(node)}</>}
